### ISSUE TITLE
Modal overlay not overlaying other kiwi components

### ISSUE THREAD

**Issue by rohanpahwa27** [kiwicom/orbit#2642] opened 2021-01-08 01:17 UTC
Use this **ONLY** for reporting bugs. For requesting new features check [this link](https://orbit.kiwi/request-an-enhancement/).

I've been trying to use a modal, but the other kiwi components I'm using do not have the overlay going on them. 

## Expected Behavior

The inputfield and button should not be active

## Current Behavior

Right now, the overlay works on everything but the inputField and button. The modal has the closebutton in it in the middle of the screen, and at the bottom, the inputfield and button are still active in the background.

## Possible Solution

Just have to fix the input field and button becoming a part of the overlay.

## Steps to Reproduce

Create an input field, button outside of the modal, and see that they're not getting overlaid. 

<img width="923" alt="Screen Shot 2021-01-07 at 8 11 40 PM" src="https://user-images.githubusercontent.com/32077634/103962322-b870ba00-5124-11eb-8451-9d07b273d4ea.png">

1. 2. 3. 4.

## Context (Environment)

I've been using react to create a web application, but this design problem is a blocker for me.

**Comment by vepor** [comment] 2021-01-08 10:20
Hello @rohanpahwa27 👋 

Could you provide us with some source code, so we can investigate the issue?

**Comment by mapsgeek** [comment] 2021-12-15 01:49
I have the same thing, anything with `z-index:1` will just overlay the modal

**Comment by silvenon** [comment] 2021-12-15 17:24
@mapsgeek we would highly appreciate some source code, preferably a demo in CodeSandbox or something 🙏 Modal has a `z-index` of 800 currently, so I think there's something else going on in your code. Messing with `z-index` is generally an anti-pattern because the z-order can also be controlled with HTML order, which is a highly recommended alternative. Also, just in case you missed it, Modals should generally be rendered inside a [Portal](https://orbit.kiwi/components/utility/portal/), that way you can easily place the Portal element to be the last one in your `<body>` (for example), so that it's always on top. If it still somehow manages to appear below another element, that can only happen if that element has a `z-index` higher than 800.

I'm closing this issue until a demo is provided reproducing this bug.

**Closed by silvenon** 2021-12-15 17:24 UTC

**Comment by mapsgeek** [comment] 2021-12-15 17:49
@silvenon totally understandable, maybe it's a wrong implementation and i will try to reorder the components and use the portal component to get around it and will provide a sandbox if necessary.
thanks

**Comment by mapsgeek** [comment] 2021-12-17 03:16
Using the [Portal ](https://orbit.kiwi/components/utility/portal/) component to wrap the modal resolved the z-index issues.
